name: sxtest-ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        phase: [4, 5, 6, 7, 8, 9, 10, 11, 12]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Test (FAZA${{ matrix.phase }})
        working-directory: ./FAZA${{ matrix.phase }}
        run: |
          if [ -f package.json ]; then
            npm ci || npm install
            npm test
          else
            echo "Nu există package.json în FAZA${{ matrix.phase }}"
          fi
